/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-actuator:2.5.9")
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.5.9")
    api("org.springframework.boot:spring-boot-starter-validation:2.5.9")
    api("org.springframework.boot:spring-boot-starter-web:2.5.9")
    api("org.springframework.boot:spring-boot-starter-security:2.5.9")
    api("org.springframework.security:spring-security-data:5.5.4")
    api("io.jsonwebtoken:jjwt-api:0.11.5")
    api("io.jsonwebtoken:jjwt-impl:0.11.5")
    api("io.jsonwebtoken:jjwt-orgjson:0.11.5")
    api("org.springframework.boot:spring-boot-starter-mail:2.5.9")
    api("org.springframework.retry:spring-retry:1.3.3")
    api("org.springframework:spring-aspects:5.3.20")
    api("org.springframework.boot:spring-boot-starter-thymeleaf:2.5.9")
    api("org.thymeleaf:thymeleaf:3.0.12.RELEASE")
    api("org.thymeleaf:thymeleaf-spring5:3.0.12.RELEASE")
    api("org.hibernate:hibernate-spatial:5.6.9.Final")
    api("javax.inject:javax.inject:1")
    api("com.fasterxml.jackson.core:jackson-databind:2.12.6")
    api("commons-beanutils:commons-beanutils:1.9.4")
    api("net.kaczmarzyk:specification-arg-resolver:2.6.2")
    runtimeOnly("org.postgresql:postgresql:42.3.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.9")
    testImplementation("org.springframework.security:spring-security-test:5.5.4")
}

group = "es"
version = "0.0.1"
description = "demo"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
jar {
  manifest {
    attributes(
      'Main-Class': 'es.Application'
    )
  }
}
