spring:
  datasource:
    url: jdbc:postgresql://dpg-chif7v1mbg557he48650-a.oregon-postgres.render.com:5432/monsteraltech
    username: udcapmonsteraltech
    password: 9bE74cT3NjoUkErlO7qfRFTyKkwPOsSn
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  host: 0.0.0.0


client:
  host: http://0.0.0.0:8080
  port: 8080
