spring:
  datasource:
    host: dpg-chif7v1mbg557he48650-a.oregon-postgres.render.com
    port: 5432
    database: monsteraltech
    username: udcapmonsteraltech
    password: 9bE74cT3NjoUkErlO7qfRFTyKkwPOsSn
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    encoding: UTF8
   
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: true
      hibernate.connection.charSet: utf-8
     # hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  # Email server configuration
  mail:
    host: 127.0.0.1
    username: dummy
    password: dummy
    port: 25
    from: no-reply@dummyserver.es
  # Email templates configuration
  thymeleaf:
    mode: HTML
    cache: true
  servlet:
    multipart:
      max-file-size: 250MB     # Set MAX_UPLOAD_FILE_SIZE in gulpfile.js
      max-request-size: 260MB  # max-file-size + 10
  sql:
    init:
      encoding: UTF-8
      mode: always
      continue-on-error: true
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  uploads: upload
  temporaryUploads: temporary
  #Default internal page size (Used for some high database usage methods)
  pageSize: 3
  port: 8080
initDB:
  defaultAdminUser: admin
  defaultAdminPassword: admin
  defaultAdminEmail: admin@localhost
logging:
  level:
    root: INFO
    es: DEBUG
    es.model.util.EnumConverter: ERROR
properties:
  clientHost: http://localhost:1234
  gis:
    defaultSrid: 4326
  environment: dev
