spring:
  datasource:
    host: dpg-chif7v1mbg557he48650-a.oregon-postgres.render.com
    port: 5432
    database: monsteraltech
    username: udcapmonsteraltech
    password: 9bE74cT3NjoUkErlO7qfRFTyKkwPOsSn
  # Email server configuration
logging:
  level:
    root: INFO
    es: DEBUG
    es.model.util.EnumConverter: ERROR
