spring:
  datasource:
    url: jdbc:postgresql://dpg-chif7v1mbg557he48650-a.oregon-postgres.render.com:5432/monsteraltech
    username: udcapmonsteraltech
    password: 9bE74cT3NjoUkErlO7qfRFTyKkwPOsSn
    driver-class-name: org.postgresql.Driver

  # Email server configuration
logging:
  level:
    root: INFO
    es: DEBUG
    es.model.util.EnumConverter: ERROR
    
server:
  uploads: upload
  temporaryUploads: temporary
  #Default internal page size (Used for some high database usage methods)
  pageSize: 3
  address: 0.0.0.0
  port: 80
